# docker build -t hgjazhgj/alas:latest -f deploy/docker/Dockerfile.cn .
# docker run -v ${PWD}:/app/AzurNext -p 25548:25548 --name AzurNext -it --rm hgjazhgj/alas

FROM python:3.14-slim-bookworm

ENV UV_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
ENV PATH=/app/AzurNext/.venv/bin:${PATH}

WORKDIR /app/AzurNext

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
COPY pyproject.toml uv.lock ./

RUN echo "\
deb https://mirrors.aliyun.com/debian/ bookworm main non-free contrib\n\
deb-src https://mirrors.aliyun.com/debian/ bookworm main non-free contrib\n\
deb https://mirrors.aliyun.com/debian-security/ bookworm-security main\n\
deb-src https://mirrors.aliyun.com/debian-security/ bookworm-security main\n\
deb https://mirrors.aliyun.com/debian/ bookworm-updates main non-free contrib\n\
deb-src https://mirrors.aliyun.com/debian/ bookworm-updates main non-free contrib" \
> /etc/apt/sources.list \
 && apt update \
 && apt install -y git adb libgomp1 libgl1 libglib2.0-0 openssh-client \
 && git config --global --add safe.directory '*' \
 && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
 && echo 'Asia/Shanghai' > /etc/timezone \
 && uv venv --relocatable --python /usr/local/bin/python .venv \
 && uv sync --frozen --no-dev --no-install-project \
 && cp /usr/local/bin/uv .venv/bin/uv \
 && cp /usr/bin/adb .venv/bin/adb \
 && cp /usr/bin/git .venv/bin/git \
 && rm -rf /root/.cache/uv

COPY . .

CMD [".venv/bin/python", "gui.py"]
